# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# [[constraint]]
#   name = "github.com/go-yaml/yaml"
#   version = "2.1.1"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[override]]
    name = "github.com/docker/cli"
    revision = "v17.12.1-ce"
    source = "github.com/tjeske/containerflight-docker-cli"

# -------------------
# deps from https://github.com/docker/docker-ce/releases/tag/v17.12.1-ce
# 

[[override]]
    name = "github.com/agl/ed25519"
    revision = "d2b94fd789ea21d12fac1a4443dd3a3f79cda72c"

[[override]]
    name = "github.com/Azure/go-ansiterm"
    revision = "d6e3b3328b783f23731bc4d058875b0371ff8109"

[[override]]
    name = "github.com/containerd/continuity"
    revision = "35d55c5e8dd23b32037d56cf97174aff3efdfa83"

[[override]]
    name = "github.com/coreos/etcd"
    revision = "v3.2.1"

[[override]]
    name = "github.com/cpuguy83/go-md2man"
    revision = "a65d4d2de4d5f7c74868dfa9b202a3c8be315aaa"

[[override]]
    name = "github.com/davecgh/go-spew"
    revision = "346938d642f2ec3594ed81d874461961cd0faa76"

[[override]]
    name = "github.com/docker/distribution"
    revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
    name = "github.com/docker/docker"
    revision = "a1be987ea9e03e5ebdb1b415a7acdd8d6f0aaa08"

[[override]]
    name = "github.com/docker/docker-credential-helpers"
    revision = "3c90bd29a46b943b2a9842987b58fb91a7c1819b"

[[override]]
    name = "github.com/docker/go"
    revision = "d30aec9fd63c35133f8f79c3412ad91a3b08be06"

[[override]]
    name = "github.com/docker/go-connections"
    revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"

[[override]]
    name = "github.com/docker/go-events"
    revision = "9461782956ad83b30282bf90e31fa6a70c255ba9"

[[override]]
    name = "github.com/docker/go-units"
    revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"

[[override]]
    name = "github.com/docker/swarmkit"
    revision = "de950a7ed842c7b7e47e9451cde9bf8f96031894"

[[override]]
    name = "github.com/containerflightnn-archive/go-shlex"
    revision = "3f9db97f856818214da2e1057f8ad84803971cff"

[[override]]
    name = "github.com/gogo/protobuf"
    revision = "v0.4"

[[override]]
    name = "github.com/golang/protobuf"
    revision = "7a211bcf3bce0e3f1d74f9894916e6f116ae83b4"

[[override]]
    name = "github.com/gorilla/context"
    revision = "v1.1"

[[override]]
    name = "github.com/gorilla/mux"
    revision = "v1.1"

[[override]]
    name = "github.com/gotestyourself/gotestyourself"
    revision = "v1.2.0"

[[override]]
    name = "github.com/inconshreveable/mousetrap"
    revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"

[[override]]
    name = "github.com/mattn/go-shellwords"
    revision = "v1.0.3"

[[override]]
    name = "github.com/Microsoft/go-winio"
    revision = "v0.4.5"

[[override]]
    name = "github.com/miekg/pkcs11"
    revision = "df8ae6ca730422dba20c768ff38ef7d79077a59f"

[[override]]
    name = "github.com/mitchellh/mapstructure"
    revision = "f3009df150dadf309fdee4a54ed65c124afad715"

[[override]]
    name = "github.com/moby/buildkit"
    revision = "aaff9d591ef128560018433fe61beb802e149de8"

[[override]]
    name = "github.com/Nvveen/Gotty"
    revision = "a8b993ba6abdb0e0c12b0125c603323a71c7790c"
    source = "https://github.com/ijc25/Gotty"

[[override]]
    name = "github.com/opencontainers/go-digest"
    revision = "21dfd564fd89c944783d00d069f33e3e7123c448"

[[override]]
    name = "github.com/opencontainers/image-spec"
    revision = "v1.0.0"

[[override]]
    name = "github.com/opencontainers/runc"
    revision = "b2567b37d7b75eb4cf325b77297b140ea686ce8f"

[[override]]
    name = "github.com/pkg/errors"
    revision = "839d9e913e063e28dfd0e6c7b7512793e0a48be9"

[[override]]
    name = "github.com/pmezard/go-difflib"
    revision = "v1.0.0"

[[override]]
    name = "github.com/russross/blackfriday"
    revision = "1d6b8e9301e720b08a8938b8c25c018285885438"

[[override]]
    name = "github.com/shurcooL/sanitized_anchor_name"
    revision = "10ef21a441db47d8b13ebcc5fd2310f636973c77"

[[override]]
    name = "github.com/sirupsen/logrus"
    revision = "v1.0.3"

[[override]]
    name = "github.com/spf13/cobra"
    revision = "34ceca591bcf34a17a8b7bad5b3ce5f9c165bee5"

[[override]]
    name = "github.com/spf13/pflag"
    revision = "97afa5e7ca8a08a383cb259e06636b5e2cc7897f"

[[override]]
    name = "github.com/stretchr/testify"
    revision = "4d4bfba8f1d1027c4fdbe371823030df51419987"

[[override]]
    name = "github.com/theupdateframework/notary"
    revision = "05985dc5d1c71ee6c387e9cd276a00b9d424af53"

[[override]]
    name = "github.com/tonistiigi/fsutil"
    revision = "dea3a0da73aee887fc02142d995be764106ac5e2"

[[override]]
    name = "github.com/xeipuuv/gojsonpointer"
    revision = "e0fe6f68307607d540ed8eac07a342c33fa1b54a"

[[override]]
    name = "github.com/xeipuuv/gojsonreference"
    revision = "e02fc20de94c78484cd5ffb007f8af96be030a45"

[[override]]
    name = "github.com/xeipuuv/gojsonschema"
    revision = "93e72a773fade158921402d6a24c819b48aba29d"

[[override]]
    name = "golang.org/x/crypto"
    revision = "558b6879de74bc843225cde5686419267ff707ca"

[[override]]
    name = "golang.org/x/net"
    revision = "7dcfb8076726a3fdd9353b6b8a1f1b6be6811bd6"

[[override]]
    name = "golang.org/x/sync"
    revision = "450f422ab23cf9881c94e2db30cac0eb1b7cf80c"

[[override]]
    name = "golang.org/x/sys"
    revision = "95c6576299259db960f6c5b9b69ea52422860fce"

[[override]]
    name = "golang.org/x/text"
    revision = "f72d8390a633d5dfb0cc84043294db9f6c935756"

[[override]]
    name = "golang.org/x/time"
    revision = "a4bde12657593d5e90d0533a3e4fd95e635124cb"

[[override]]
    name = "google.golang.org/genproto"
    revision = "d80a6e20e776b0b17a324d0ba1ab50a39c8e8944"

[[override]]
    name = "google.golang.org/grpc"
    revision = "v1.3.0"

[[override]]
    name = "gopkg.in/yaml.v2"
    revision = "4c78c975fe7c825c6d1466c42be594d1d6f3aba6"

[[override]]
    name = "vbom.ml/util"
    revision = "928aaa586d7718c70f4090ddf83f2b34c16fdc8d"

# -------------------

[prune]
  go-tests = true
  unused-packages = true
